### ISSUE TITLE
consider highlightjs vs. prismjs?

### ISSUE THREAD

**Issue by mackenza** [vlucas/devdata.io#10]
I see prismjs doesn't support `lua` and highlightjs does. We might want to consider changing since lua is now part of the site.

**Comment by vlucas** [comment]
I agree. Also Prism.js is crazy slow on larger data sets (try the airport codes one).

**Comment by mackenza** [comment]
I may be able to get a pr for this tonight, though I am not very familiar with jade templates... very terse ;)

**Comment by mackenza** [comment]
I have it ready to go, but I am going to wait for you to merge the dart language as I kinda screwed up my branches again and polluted master :( git vexes me sometimes!

**Comment by mackenza** [comment]
it seems faster than prism, though there is still a slight delay on the airport-codes set when switching

**Comment by mackenza** [comment]
PR #12 closes this.
