### ISSUE TITLE
Need to add support for static types?

### ISSUE THREAD

**Issue by mackenza** [vlucas/devdata.io#4]
@vlucas I was wondering about the static typing issue. Should someone be creating a PR to accept static types for the languages that support them? Even Hack/PHP7 would benefit from this. I was thinking of adding Typescript as a language but don't see the benefit without the types.

**Comment by mackenza** [comment]
I was thinking about this last night and the example I gave around Typescript may not be a good one. Since Typescript transpiles down to Javascript and the typing is for compile-time, it may not be important for a dataset to have static typing as, presumably, the datasets conform to consistent types and therefore don't really benefit from the static typing in TS.

I think it would be a different story for languages that need static types to actually compile.

**Comment by vlucas** [comment]
A good language to try this with might be Go, Java, C, Objective-C, Swift, etc. I am definitely not against supporting static languages, but I know it will add a bit of complexity to the code - we may consider having a separate set of rules or formatting logic for static languages.
