### ISSUE TITLE
adding languages

### ISSUE THREAD

**Issue by mackenza** [vlucas/devdata.io#9]
@vlucas are you handling the css (different colors per language) and the prismjs dependencies for new languages? i.e. we just need to change converter.js and app.js?

**Comment by mackenza** [comment]
the reason I bring up prismjs is because I was adding `Dart` and while prismjs supports it, it's not part of the build you got for it.

**Comment by vlucas** [comment]
I did add in CSS for Lua manually. C# does not appear to have any official logo or colors from Microsoft so I didn't add any CSS for that, but I only did a cursory Google search.

**Comment by mackenza** [comment]
got it... if there are "official" colours for a language we can add them
